CREATE TABLE tour (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(200),
    mountain_range          VARCHAR(200),
    country_code            VARCHAR(2),
    start_location_name     VARCHAR(200),
    start_latitude          NUMERIC(9, 7),
    start_longitude         NUMERIC(10, 7),
    short_description       VARCHAR(500),
    technical_description   VARCHAR(10000),
    distance_km             NUMERIC(8, 2),
    total_ascent_m          INTEGER,
    total_descent_m         INTEGER,
    lowest_point_m          INTEGER,
    highest_point_m         INTEGER,
    duration_min_hours      NUMERIC(4, 1),
    duration_max_hours      NUMERIC(4, 1),
    tour_date               DATE,
    technical_difficulty    VARCHAR(2),
    physical_difficulty     INTEGER,
    exposure_rating         VARCHAR(2),
    scenic_rating           INTEGER,
    carrying_percentage     INTEGER,
    route_type              VARCHAR(30),
    cover_photo_id          BIGINT UNIQUE,
    youtube_video_id        VARCHAR(20),
    publication_status      VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at            TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT chk_tour_title
        CHECK (title IS NULL OR BTRIM(title) <> ''),
    CONSTRAINT chk_tour_mountain_range
        CHECK (mountain_range IS NULL OR BTRIM(mountain_range) <> ''),
    CONSTRAINT chk_tour_country_code
        CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT chk_tour_start_location
        CHECK (
            (start_location_name IS NULL AND start_latitude IS NULL AND start_longitude IS NULL)
            OR
            (start_location_name IS NOT NULL
                AND BTRIM(start_location_name) <> ''
                AND start_latitude BETWEEN -90 AND 90
                AND start_longitude BETWEEN -180 AND 180)
        ),
    CONSTRAINT chk_tour_short_description
        CHECK (short_description IS NULL OR BTRIM(short_description) <> ''),
    CONSTRAINT chk_tour_technical_description
        CHECK (technical_description IS NULL OR BTRIM(technical_description) <> ''),
    CONSTRAINT chk_tour_statistics_complete
        CHECK (
            (distance_km IS NULL
                AND total_ascent_m IS NULL
                AND total_descent_m IS NULL
                AND lowest_point_m IS NULL
                AND highest_point_m IS NULL)
            OR
            (distance_km IS NOT NULL
                AND total_ascent_m IS NOT NULL
                AND total_descent_m IS NOT NULL
                AND lowest_point_m IS NOT NULL
                AND highest_point_m IS NOT NULL)
        ),
    CONSTRAINT chk_tour_statistics_values
        CHECK (
            distance_km IS NULL
            OR
            (distance_km >= 0
                AND total_ascent_m >= 0
                AND total_descent_m >= 0
                AND highest_point_m >= lowest_point_m)
        ),
    CONSTRAINT chk_tour_duration_complete
        CHECK (
            (duration_min_hours IS NULL AND duration_max_hours IS NULL)
            OR
            (duration_min_hours IS NOT NULL AND duration_max_hours IS NOT NULL)
        ),
    CONSTRAINT chk_tour_duration_values
        CHECK (
            duration_min_hours IS NULL
            OR
            (duration_min_hours > 0
                AND duration_max_hours >= duration_min_hours
                AND MOD(duration_min_hours, 0.5) = 0
                AND MOD(duration_max_hours, 0.5) = 0)
        ),
    CONSTRAINT chk_tour_technical_difficulty
        CHECK (technical_difficulty IS NULL OR technical_difficulty IN ('S0', 'S1', 'S2', 'S3', 'S4', 'S5')),
    CONSTRAINT chk_tour_physical_difficulty
        CHECK (physical_difficulty IS NULL OR physical_difficulty BETWEEN 1 AND 5),
    CONSTRAINT chk_tour_exposure_rating
        CHECK (exposure_rating IS NULL OR exposure_rating IN ('E1', 'E2', 'E3', 'E4')),
    CONSTRAINT chk_tour_scenic_rating
        CHECK (scenic_rating IS NULL OR scenic_rating BETWEEN 1 AND 5),
    CONSTRAINT chk_tour_carrying_percentage
        CHECK (carrying_percentage IS NULL OR carrying_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_tour_route_type
        CHECK (route_type IS NULL OR route_type IN ('LOOP', 'POINT_TO_POINT')),
    CONSTRAINT chk_tour_youtube_video_id
        CHECK (youtube_video_id IS NULL OR youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'),
    CONSTRAINT chk_tour_publication_status
        CHECK (publication_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT chk_tour_publication_timestamp
        CHECK (
            (publication_status = 'DRAFT' AND published_at IS NULL)
            OR
            (publication_status = 'PUBLISHED' AND published_at IS NOT NULL)
        )
);

CREATE TABLE gpx_track (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id             BIGINT NOT NULL UNIQUE,
    original_filename   VARCHAR(255) NOT NULL,
    source_reference    VARCHAR(1000) NOT NULL,

    CONSTRAINT fk_gpx_track_tour
        FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE,
    CONSTRAINT chk_gpx_track_original_filename
        CHECK (BTRIM(original_filename) <> ''),
    CONSTRAINT chk_gpx_track_source_reference
        CHECK (BTRIM(source_reference) <> '')
);

CREATE TABLE tour_photo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id           BIGINT NOT NULL,
    image_reference   VARCHAR(1000) NOT NULL,
    caption           VARCHAR(500),
    display_order     INTEGER NOT NULL,

    CONSTRAINT fk_tour_photo_tour
        FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE,
    CONSTRAINT uq_tour_photo_display_order
        UNIQUE (tour_id, display_order),
    CONSTRAINT uq_tour_photo_id_and_tour
        UNIQUE (id, tour_id),
    CONSTRAINT chk_tour_photo_image_reference
        CHECK (BTRIM(image_reference) <> ''),
    CONSTRAINT chk_tour_photo_caption
        CHECK (caption IS NULL OR BTRIM(caption) <> ''),
    CONSTRAINT chk_tour_photo_display_order
        CHECK (display_order >= 0)
);

ALTER TABLE tour
    ADD CONSTRAINT fk_tour_cover_photo
    FOREIGN KEY (cover_photo_id, id)
    REFERENCES tour_photo (id, tour_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE tour_bike_type (
    tour_id     BIGINT NOT NULL,
    bike_type   VARCHAR(30) NOT NULL,

    CONSTRAINT pk_tour_bike_type
        PRIMARY KEY (tour_id, bike_type),
    CONSTRAINT fk_tour_bike_type_tour
        FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE,
    CONSTRAINT chk_tour_bike_type
        CHECK (bike_type IN ('GRAVEL', 'XC', 'ALL_MOUNTAIN', 'ENDURO'))
);

CREATE TABLE tour_surface_share (
    tour_id         BIGINT NOT NULL,
    surface_order   INTEGER NOT NULL,
    surface_type    VARCHAR(30) NOT NULL,
    percentage      INTEGER NOT NULL,

    CONSTRAINT pk_tour_surface_share
        PRIMARY KEY (tour_id, surface_order),
    CONSTRAINT fk_tour_surface_share_tour
        FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE,
    CONSTRAINT uq_tour_surface_share_type
        UNIQUE (tour_id, surface_type),
    CONSTRAINT chk_tour_surface_share_order
        CHECK (surface_order >= 0),
    CONSTRAINT chk_tour_surface_share_type
        CHECK (surface_type IN ('ASPHALT', 'GRAVEL', 'FOREST_ROAD', 'SINGLETRACK', 'DOUBLETRACK')),
    CONSTRAINT chk_tour_surface_share_percentage
        CHECK (percentage BETWEEN 0 AND 100)
);

CREATE TABLE tour_elevation_profile (
    tour_id       BIGINT NOT NULL,
    sample_index  INTEGER NOT NULL,
    distance_km   NUMERIC(10, 3) NOT NULL,
    elevation_m   INTEGER NOT NULL,

    CONSTRAINT pk_tour_elevation_profile
        PRIMARY KEY (tour_id, sample_index),
    CONSTRAINT fk_tour_elevation_profile_tour
        FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE,
    CONSTRAINT chk_tour_elevation_profile_index
        CHECK (sample_index >= 0),
    CONSTRAINT chk_tour_elevation_profile_distance
        CHECK (distance_km >= 0)
);
